#!/usr/bin/env python3
import base64
import re
import struct
import sys
from pathlib import Path

EXPECTED_REV = "6dce57eef127dc4cc292644f38196e0e7c58590c"
PAL_B64 = "AADYYlVarkFrNcYgEUoTIJ8AI0AMZYogzDgAAAAAAAA="
TILEMAP_B64 = "ARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARACEAMQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAFEAEQBhAHEAgQCBAIEAgQCBAIEAgQCBAIEAgQCBAIEAgQCBAIEAgQCBAIEAgQCBAIEAgQCBAIEAgQCBAIEAgQCRABEAYQBxAKEAoQChAKEAsQCxALEAsQCxALEAsQCxALEAsQCxALEAsQCxALEAsQCxALEAsQCxAMEAoQChAKEAkQARAGEAcQDRANEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRAJEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEA0QCRABEAYQBxANEA0QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QDRANEAkQARAGEAcQDRANEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRAJEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEA0QCRABEAYQBxANEA8QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QDRANEAkQARAGEAcQDRAQEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRAJEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEA0QCRABEAYQBxANEA0QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QDRANEAkQARAGEAcQDRANEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRAJEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEA0QCRABEAYQBxANEA0QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QDRANEAkQARAGEAcQDRANEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRAJEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEA0QCRABEAYQBxANEA0QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QDRANEAkQARAGEAcQDRANEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRAJEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEA0QCRABEAYQBxANEA0QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QDRANEBEQARAGEAcQDRANEA0QDRAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQDhANEA0QDRASEAEQBhAHEA0QDRANEA0QABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA4QDRANEBMQFBABEAYQBxANEA0QDRANEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAOEA0QFRAWEBcQARAYEBkQGhAaEBoQGhAbEBsQGxAbEBsQGxAbEBsQGxAbEBsQGxAbEBsQGxAbEBsQGxAbEBsQHBAdEB4QHxABEAEQARAgECEQIRAhECEQIRAhECEQIRAhECEQIRAhECEQIRAhECEQIRAhECEQIRAhECEQIRAhECIQIxABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABECQQJRAmECcQKBApECoQKxAsEC0QLhAvEDAQMRAyEDMQNBA1EDYQNxA4EDkQARABEAEQARABEAEQARABEAEQOhA7EDwQPRA+ED8QQBBBEEIQQxBEEEUQRhBHEEgQSRBKEEsQTBBNEE4QTxBQEDoQOhA6EDoQOhA6EDoQOhA6EA=="
CHARDATA_B64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AP8A/wD/AP8A/wD/AP8AAAAAAAAAAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/gEAAAAAAAAAAAAAAAAAAAEA/wDwD+MYziCQQSGGY4xHCAAAAAAHAB8APwB/AH8A/wD/AP///wAAAAD//wD/AP8AAAAAAP8A/wD/AP8A/wD/AP8AD/DHGDMECQIAweAh4AEAAAAA4AD4APwA+gDaAPsA/gH+Af4B/gH+Af4B/gH+AQEAAQABAAEAAQABAAEAAQBPEE8QTxBPEE8QTxBPEE8Q/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP//AAD/AP8A/wD/AP8A/wD/AAD//wD/AAD/4AHgAeAB4AHgAeAB4AHgAfsA+wD7APsA+wD7APsA+wAA//8A/wD/AP8A/wD/AP8AAP//AP8A/wD/AP8A/wD/AAD//wD/AP8A/wD/AP8AAAAA//8A/wD/AP8A/wD/AAAAAP//AP8A/wD/AP8A/wC/AAD//wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AL8AvwC/AL8AvwC/AL8AvwD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A8zD9fMbGgoK6gv8A/wD/APMA/QDGOIJ8gkSKgsaC/UT5CMMA/wD/AP8AgnTGOP0A+QDDAP8A/wD/AOAB4AHgAeAB4AHgAeAB4wL7APsA+wD7APsA+wD7APgA4wLjAuEC4QLhAsUGwwTDBPgA+AD6APgA+ADwAPQA9AD/AP8A/wD/AP8A/gD8APgA/wD/AP8A/wD/AP8A/wD/AIcIhwiHCA8QLzAfIB8gP0DoAOgAwADQAIAAoACAAEAA/wD/AP8A/wD/AP8A/gD8AP8A/wD/AP8A/wD/AP8A/wD4APEB4AHBAoMEAwwHGB8g/gD8AP0A+gD0AOgA0ACgAP+Af4D/AP8A/wD/AP8A/wAAAAAAAAAAAAAAAAAAAAAA/gH+Af4B/wD/AP8A/wD/AAEAAQABAAAAAAAAAAAAAABPEE8QTxBPEMeIY4CwQLxg/wD/AP8A/wB/AP8AfwAfAP8A/wD/AP8A/wD/AP8AAAD/AP8A/wD/AP8A/wD/AP8AAAD/AP8A/wD/AP8A/wAAAP8A/wD/AP8A/wD/AP8A/wA/AP8A/wD/AP8A/wD4AAAA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP4A8ACAAAEBSQ7/AP8A/wD/AP8A/gDwAMYA8ADgAIIDAQYHGF9gP8D/AP8A/AD4AOQAkAAgAIAAAAA/QH+A/wD/AP8A/wD/AP8AQACAAAAAAAAAAAAAAAAAAO4Q8gz8A/8A/wD/AP8A/wAfAA4AAQAAAAAAAAAAAAAAAAAAAAD//wD/AP8A/wD/AP8AAAD/AAAAAAAAAAAAAAAEAAAHA/z/AP8A/wD/AP8A/AAHAPAAAAAAAAAAAAAAAEd4f4D/AP8A/wD/AP8A/wAwAAAAAAAAAAAAAAAAAAAA/wD4B/sG+wb7BvsG+wb7BgAAAAAAAwADAAMAAwADAAP/ABDv12jnOOcc9xzfSN9gAAAAACDHAOcQ5wj3IP8g3/8AB/h/yDewAP87jHvMe8wAAAAAgHjIePgAxHuEe4R7/wD/AP8A/QMD/L1H/SOdcwAAAAAAAAIBCAMCuQLdYp3/AP8AP8DdIuAQxyLMI98iAAAAAMAAIMAP7zjfM9wg3/8A/wD/AP8AYJ+d4t9h3KMAAAAAAAAAAIAAAJ0A3gPc/wD/AP8A/wAY5+M+5w32mQAAAAAAAAAAQwAAwxD3Afb/AI9w/0B/gHyD+4b3jHfIAAAAAABwAHCDcATzCPeId/8A/wD/AP8Az/D3GDvMO8QAAAAAAAAAADDACPDEOMQ4/wD9AvsE9wj+AO0Q/xD/BAAAAgEEAwgHAQ8SDgAcABw/wP8BwQE/AP8A/wD/AP8AwD8A/z7/wMAAAAAAAAAAAP8L7xD/EN8g/yS7TLcI8wwADxAPAB8gHwA/BDtAcwhze4R7BHsA/4D3iPeAvsi8QYQDhIOEhwCHCIcIj0GPQ467RLdItwi3APcA/wDsAMogRINIh0jHSM8IzwDPE9813bcAtwC3ALYBtgG+Ce8Q7xBIz0jPSM9JzkjOQM4QzxDP+wT/AP/g/wD/AP8A7xDvEAD4APgA+AAAAAAAABDgEODfD79gv0+/SL9Ivwi/AP9AID8AP0A/QDhAOEB4QH8Afz9A3wHvEmsEb4RnGPcp1iGAgCDhEOOU85B3gOcI5wnOec7+Au4gt0x7hHuE/wL/AoR5Af8R/0iHhAOEAwADAAPeIe8RfRI3iL/E34Heod2gIcAQ4YLxyHMAvyC/AJ4Cnv8g/yC/AP8Af4D/AP8AgH8A4ADgQMAAgIAAAAAAAH8A/wD/AP8A/wD/AP8A/wBHuAAAAAAAAAAAAAAAAAAAuAD/AP8A/wD/AP8A/wD/AAAAAAAAAAAAAAAAAAAAAAAAAPsG+wb5BPgH/wD/AP8AAAAAAwADAgMAAAAAAAAAAAAAz3DvWLcMMM//AP8A/wAAAADPAM9Ixw8AAAAAAAAAAAB7zHvMO4wA//8A/wD/AAAAhHuEe8R7+AAAAAAAAAAAAJ1zvVO9U2Ge/wD/AP8AAAACnQKdAp0AAAAAAAAAAAAA3CfMJ8cyOMf/AP8A/wAAACPcMdwoz8AAAAAAAAAAAAAc490inWLhHv8A/wD/AAAAwBwA3CCcHAAAAAAAAAAAAPaZ953znAn3/wD/AP8AAAAB9gD3DPPyAQAAAAAAAAAAd8h3zPuGvHP/AP8A/wAAAAh3iHcE80OwAAAAAAAAAAA7xDvM8xzH+P8A/wD/AAAAxDjEOAjwMMAAAAAAAAAAAPsA/wT/EO8S/wj3DPkFAAAEHAAcABwQDgAPCAcGAwAAv0K9QMwjzSO/oP8A9/sAAEA+Qj4THDIdQP8A/wj3AAB/iP8AwR3dIv9AvkD+gAAAgH8A/z7jAMEAwQGBAYEAALxBvRK5AvkC+wTzBAMEAABDjkLcRtwG/AT4DPj8+AAA2gD+APYAfgBuAG4QHgAAACX9AfkJ+YHxkfGR4eHhAADsEO0Q7RLtAswg7yD/IAAAE88SzhDMENwz3xDfAP8AAC8Q/wD/AP8ADxDvEO8QAADA4AAAAAAAAPDgAOAA4AAA/1//EH+Qf5BxH38A/4EAAAB/AHAAcIBwjvGA/wD/AADmEeaRZ4lnCOsQ3yI+QAAAGe4Z7ph3mPcU5yDDgYEAAP8A+wT/BHeBjuH9AvM0AAAAAwQDAAeID1CeAvwI+AAA36BfJFug3yTfJN8k3yQAAACcgJwEHAAcABwAHAAcAAC5RtUq1SrVKsQ7/wD/AAAARjkqEQIRAhETAAAAAAAAALdI9wgXqBfoR7j/AP8AAABIsMgw6BDoELgAAAAAAAAA"

def fmt_u8(data, per=16):
    vals = [f"0x{b:02X}" for b in data]
    return "\n".join("\t" + ", ".join(vals[i:i+per]) + "," for i in range(0, len(vals), per))

def fmt_u16le(data, per=8):
    vals = [f"0x{struct.unpack_from('<H', data, i)[0]:04X}" for i in range(0, len(data), 2)]
    return "\n".join("\t" + ", ".join(vals[i:i+per]) + "," for i in range(0, len(vals), per))

def replace_one(src, pattern, replacement, label):
    out, n = re.subn(pattern, replacement, src, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f"ERROR: expected exactly one {label} array, found {n}")
    return out

def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: patch_mgba_sgb1_border.py PATH_TO_src/gb/video.c")
    p = Path(sys.argv[1])
    src = p.read_text(encoding="utf-8")
    if "ORIGINAL_SGB1_HOST_BORDER" in src:
        print("patch already present")
        return

    pal = base64.b64decode(PAL_B64)
    tm = base64.b64decode(TILEMAP_B64)
    char = base64.b64decode(CHARDATA_B64)
    assert len(pal) == 32
    assert len(tm) == 1792
    assert len(char) == 2592

    palette = (
        "/* ORIGINAL_SGB1_HOST_BORDER: exact 256x224 Super Game Boy 1 host frame */\n"
        "static const uint16_t _defaultBorderPalette[16] = {\n"
        + fmt_u16le(pal) + "\n};"
    )
    tilemap = "static const uint8_t _defaultBorderTilemap[] = {\n" + fmt_u8(tm) + "\n};"
    chardata = "static const uint8_t _defaultBorderChardata[] = {\n" + fmt_u8(char) + "\n};"

    src = replace_one(
        src,
        r"static const uint16_t _defaultBorderPalette\[16\]\s*=\s*\{.*?\n\};",
        palette,
        "_defaultBorderPalette",
    )
    src = replace_one(
        src,
        r"static const uint8_t _defaultBorderTilemap\[\]\s*=\s*\{.*?\n\};",
        tilemap,
        "_defaultBorderTilemap",
    )
    src = replace_one(
        src,
        r"static const uint8_t _defaultBorderChardata\[\]\s*=\s*\{.*?\n\};",
        chardata,
        "_defaultBorderChardata",
    )
    p.write_text(src, encoding="utf-8")
    print("Integrated original SGB1 host border")
    print("revision:", EXPECTED_REV)
    print("palette: 16 colors; tilemap: 1792 bytes; char data: 2592 bytes / 81 tiles")

if __name__ == "__main__":
    main()
